<script src="//wt-js.translate.com/translate.js" type="text/javascript"></script>

<?php

$defaults = array(
  'remember_language' => 'true',
  'guess_language' => 'true',
  'translate_meta' => 'true',
  'localize_images' => 'false',
  'localize_bg_images' => 'false',
  'localize_media' => 'false'
);

$model = Mage::getModel('websitetranslator/websitetranslator');

$settings = array();

foreach ($defaults as $setting_name => $default_value)
{
  $item = $model->load($setting_name, 'setting_name');
  $settings[$setting_name] = $item->getSettingValue();
}

$settings = array_diff_assoc($settings, $defaults);

$script .= '<script type="text/javascript">'."\n\t".'TranslateJS.init({';

$website_key = $model->load('website_key', 'setting_name')->getSettingValue();
$script .= "\n\t\t" . '"key": "' . $website_key . '",';

foreach ($settings as $key => $value)
{
  $script .= "\n\t\t" . '"'. $key . '": ' . $value .',';
}

$script .= "\n\t});\n". '</script>';

// Remove the last comma in the string
$last_comma = strrpos($script, ",");
$script = substr_replace($script, "", $last_comma, 1);

echo $script;

?>
